"""changes to word

Revision ID: 42e40a1be1c7
Revises: ea92212b4638
Create Date: 2023-03-28 16:28:40.640860

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '42e40a1be1c7'
down_revision = 'ea92212b4638'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('word', schema=None) as batch_op:
        batch_op.add_column(sa.Column('part_of_speech', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('example', sa.String(length=200), nullable=True))
        batch_op.drop_constraint('word_meaning_key', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('word', schema=None) as batch_op:
        batch_op.create_unique_constraint('word_meaning_key', ['meaning'])
        batch_op.drop_column('example')
        batch_op.drop_column('part_of_speech')

    # ### end Alembic commands ###
