"""remove words from prompts

Revision ID: 6b297a302b01
Revises: 9c53bfa19e64
Create Date: 2023-03-29 12:10:16.216191

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6b297a302b01'
down_revision = '9c53bfa19e64'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('word_prompt', schema=None) as batch_op:
        batch_op.drop_constraint('word_prompt_word_id_fkey', type_='foreignkey')
        batch_op.drop_column('word_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('word_prompt', schema=None) as batch_op:
        batch_op.add_column(sa.Column('word_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('word_prompt_word_id_fkey', 'word', ['word_id'], ['id'])

    # ### end Alembic commands ###
