"""table for word root

Revision ID: 9c53bfa19e64
Revises: 0dd21ab85eb5
Create Date: 2023-03-28 17:00:08.287465

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9c53bfa19e64'
down_revision = '0dd21ab85eb5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('root',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('meaning', sa.String(length=1000), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('word', schema=None) as batch_op:
        batch_op.add_column(sa.Column('root_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'root', ['root_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('word', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('root_id')

    op.drop_table('root')
    # ### end Alembic commands ###
